language: python
services:
  - docker
before_install:
  - docker pull ashwoods/gst-base:1.16.2
install:
  - docker-compose build
script:
  - docker-compose run test
after_script:
  - bash <(curl -s https://codecov.io/bash)
